# Site settings
title: Turing Research
email: hello@turingres.com
description: > # this means to ignore newlines until "baseurl:"
  Turing Research Inc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site


# Build settings
markdown: kramdown


paginate: 4
paginate_path: "blog/page:num"
